import type { ReactNode } from "react";

import { AgentPatternCanvas, type AgentPatternConfig } from "./agent-pattern-canvas";

const config: AgentPatternConfig = {
  title: "Advisor Strategy",
  subtitle: "A high-capability advisor plans and checks; cheaper executors do the volume work.",
  tone: "lime",
  initialScenarioId: "busy",
  initialPace: "busy",
  scenarios: [
    {
      id: "busy",
      label: "busy",
      caption:
        "A production advisor split has routing, parallel executors, retries, and review all moving at once.",
      nodes: [
        {
          id: "queue",
          label: "Queue",
          detail: "Mixed requests arrive with different risk, cost, and ambiguity profiles.",
          x: 0.08,
          y: 0.52,
          type: "user",
        },
        {
          id: "router",
          label: "Router",
          detail: "Rules and cheap classifiers split easy work from uncertain work.",
          x: 0.34,
          y: 0.52,
          type: "tool",
        },
        {
          id: "planner",
          label: "Planner",
          detail: "A planning step turns hard requests into instructions for cheaper executors.",
          x: 0.35,
          y: 0.25,
          type: "control",
        },
        {
          id: "plan",
          label: "Plan",
          detail: "A compact plan becomes instructions that cheaper models can execute.",
          x: 0.48,
          y: 0.39,
          type: "state",
        },
        {
          id: "haiku",
          label: "Haiku",
          detail: "Fast extraction, classification, normalization, and other high-volume chores.",
          x: 0.46,
          y: 0.68,
          type: "worker",
        },
        {
          id: "sonnet",
          label: "Sonnet",
          detail: "The default executor handles drafting and moderate reasoning.",
          x: 0.63,
          y: 0.52,
          type: "worker",
        },
        {
          id: "gate",
          label: "Gate",
          detail: "Confidence, retries, policy flags, and rubric scores decide what escalates.",
          x: 0.78,
          y: 0.66,
          type: "review",
        },
        {
          id: "opus",
          label: "Opus",
          detail: "Escalated cases get premium review before retry or delivery.",
          x: 0.76,
          y: 0.31,
          type: "control",
        },
        {
          id: "done",
          label: "Output",
          detail: "Only the expensive decisions take the expensive path.",
          x: 0.93,
          y: 0.52,
          type: "state",
        },
      ],
      edges: [
        { from: "queue", to: "router", label: "classify" },
        { from: "router", to: "planner", label: "hard" },
        { from: "router", to: "haiku", label: "easy" },
        { from: "planner", to: "plan", label: "strategy" },
        { from: "plan", to: "sonnet", label: "draft" },
        { from: "plan", to: "haiku", label: "extract", bend: 22 },
        { from: "haiku", to: "gate", label: "facts" },
        { from: "sonnet", to: "gate", label: "candidate" },
        { from: "gate", to: "opus", label: "escalate", bend: -46, dashed: true },
        { from: "opus", to: "sonnet", label: "retry", bend: 54, dashed: true },
        { from: "gate", to: "done", label: "ship" },
        { from: "opus", to: "done", label: "approve" },
      ],
      metrics: [
        { label: "judgment used", value: 0.78 },
        { label: "cost pressure", value: 0.52 },
        { label: "routing complexity", value: 0.88 },
      ],
    },
    {
      id: "baseline",
      label: "baseline",
      caption:
        "One expensive model handles every step, including the parts that need little judgment.",
      nodes: [
        {
          id: "task",
          label: "Task",
          detail: "Incoming work enters a single-model pipeline.",
          x: 0.08,
          y: 0.48,
          type: "user",
        },
        {
          id: "plan",
          label: "Plan",
          detail: "The same premium model spends a full turn deciding the shape of the work.",
          x: 0.26,
          y: 0.28,
          type: "control",
        },
        {
          id: "extract",
          label: "Extract",
          detail: "Even routine parsing runs through the expensive path.",
          x: 0.42,
          y: 0.62,
          type: "control",
        },
        {
          id: "draft",
          label: "Draft",
          detail: "Generation, transformation, and retry work all use the same model tier.",
          x: 0.6,
          y: 0.38,
          type: "control",
        },
        {
          id: "review",
          label: "Review",
          detail: "The model checks its own work without a cheaper first-pass filter.",
          x: 0.76,
          y: 0.62,
          type: "review",
        },
        {
          id: "done",
          label: "Output",
          detail: "Quality can be high, but routine steps pay the full reasoning price.",
          x: 0.94,
          y: 0.48,
          type: "state",
        },
      ],
      edges: [
        { from: "task", to: "plan", label: "scope" },
        { from: "plan", to: "extract", label: "parse" },
        { from: "extract", to: "draft", label: "context" },
        { from: "draft", to: "review", label: "check" },
        { from: "review", to: "draft", label: "retry", bend: 42, dashed: true },
        { from: "review", to: "done", label: "deliver" },
      ],
      metrics: [
        { label: "judgment used", value: 0.82 },
        { label: "cost pressure", value: 0.88 },
        { label: "routing complexity", value: 0.18 },
      ],
    },
    {
      id: "advisor",
      label: "advisor",
      caption:
        "A planning step writes the plan, executors run it, and escalation handles uncertainty.",
      nodes: [
        {
          id: "task",
          label: "Task",
          detail: "The initial prompt is evaluated for shape, risk, and decomposition.",
          x: 0.08,
          y: 0.5,
          type: "user",
        },
        {
          id: "router",
          label: "Router",
          detail: "Rules split routine work from ambiguous work before the advisor spends tokens.",
          x: 0.34,
          y: 0.5,
          type: "tool",
        },
        {
          id: "planner",
          label: "Planner",
          detail: "A planning step spends premium-model tokens before executor work begins.",
          x: 0.38,
          y: 0.24,
          type: "control",
        },
        {
          id: "haiku",
          label: "Haiku",
          detail: "The fastest model handles structured extraction and simple classification.",
          x: 0.48,
          y: 0.68,
          type: "worker",
        },
        {
          id: "sonnet",
          label: "Sonnet",
          detail: "The default executor handles drafting and moderate reasoning.",
          x: 0.62,
          y: 0.48,
          type: "worker",
        },
        {
          id: "gate",
          label: "Gate",
          detail: "A rule, confidence score, or rubric decides whether to escalate.",
          x: 0.78,
          y: 0.62,
          type: "review",
        },
        {
          id: "opus",
          label: "Opus",
          detail: "Escalations get premium review, correction, or a new plan.",
          x: 0.8,
          y: 0.26,
          type: "control",
        },
        {
          id: "done",
          label: "Output",
          detail: "Only the steps that need judgment pay the premium-model cost.",
          x: 0.94,
          y: 0.5,
          type: "state",
        },
      ],
      edges: [
        { from: "task", to: "router", label: "classify" },
        { from: "router", to: "planner", label: "plan" },
        { from: "router", to: "haiku", label: "simple" },
        { from: "planner", to: "sonnet", label: "instructions" },
        { from: "haiku", to: "gate", label: "facts" },
        { from: "sonnet", to: "gate", label: "confidence" },
        { from: "gate", to: "opus", label: "escalate", bend: -46, dashed: true },
        { from: "opus", to: "sonnet", label: "retry", bend: 52, dashed: true },
        { from: "gate", to: "done", label: "pass" },
        { from: "opus", to: "done", label: "approve" },
      ],
      metrics: [
        { label: "judgment used", value: 0.74 },
        { label: "cost pressure", value: 0.48 },
        { label: "routing complexity", value: 0.58 },
      ],
    },
    {
      id: "overuse",
      label: "overuse",
      caption:
        "Broad escalation turns the advisor pattern into baseline execution plus routing overhead.",
      nodes: [
        {
          id: "task",
          label: "Messy input",
          detail: "Ambiguous work needs real judgment across most steps.",
          x: 0.08,
          y: 0.5,
          type: "user",
        },
        {
          id: "router",
          label: "Router",
          detail: "The router cannot separate simple and hard cases cleanly.",
          x: 0.34,
          y: 0.5,
          type: "tool",
        },
        {
          id: "executor",
          label: "Executor",
          detail: "The cheap model keeps flagging uncertainty instead of making progress.",
          x: 0.42,
          y: 0.66,
          type: "worker",
        },
        {
          id: "advisor",
          label: "Advisor",
          detail: "Escalation is now the common path, so cost and latency climb again.",
          x: 0.48,
          y: 0.28,
          type: "control",
        },
        {
          id: "review",
          label: "Review",
          detail: "A mandatory quality gate catches issues, but it is no longer selective.",
          x: 0.72,
          y: 0.52,
          type: "review",
        },
        {
          id: "rewrite",
          label: "Rewrite",
          detail: "Corrective instructions pile up and the executor keeps retrying.",
          x: 0.66,
          y: 0.78,
          type: "state",
        },
        {
          id: "done",
          label: "Late output",
          detail: "The workflow ships, but it behaved like baseline plus orchestration overhead.",
          x: 0.94,
          y: 0.52,
          type: "state",
        },
      ],
      edges: [
        { from: "task", to: "router", label: "classify" },
        { from: "router", to: "executor", label: "try" },
        { from: "router", to: "advisor", label: "unclear", dashed: true },
        { from: "executor", to: "advisor", label: "low confidence", dashed: true },
        { from: "advisor", to: "executor", label: "retry", bend: 42, dashed: true },
        { from: "executor", to: "review", label: "draft" },
        { from: "review", to: "advisor", label: "fix", bend: -42, dashed: true },
        { from: "review", to: "rewrite", label: "notes" },
        { from: "rewrite", to: "executor", label: "again", bend: 46, dashed: true },
        { from: "review", to: "done", label: "ship" },
      ],
      metrics: [
        { label: "judgment used", value: 0.86 },
        { label: "cost pressure", value: 0.78 },
        { label: "routing complexity", value: 0.82 },
      ],
    },
  ],
};

export function AdvisorStrategy({ info }: { info?: ReactNode }) {
  return <AgentPatternCanvas config={config} info={info} />;
}
