import type { ReactNode } from "react";

import { AgentPatternCanvas, type AgentPatternConfig } from "./agent-pattern-canvas";

const config: AgentPatternConfig = {
  title: "Hooks",
  subtitle:
    "Deterministic callbacks run at lifecycle boundaries before, during, or after agent work.",
  tone: "red",
  initialScenarioId: "guard",
  initialPace: "busy",
  scenarios: [
    {
      id: "guard",
      label: "guard",
      caption: "A pre-tool hook checks the attempted action before the agent can mutate state.",
      nodes: [
        {
          id: "request",
          label: "Refund request",
          detail: "The user asks for a refund review that may end in a write action.",
          x: 0.08,
          y: 0.5,
          type: "user",
        },
        {
          id: "agent",
          label: "Agent",
          detail: "The agent proposes a tool call after reading policy and account state.",
          x: 0.31,
          y: 0.5,
          type: "worker",
        },
        {
          id: "hook",
          label: "PreToolUse",
          detail: "A deterministic check inspects tool name, arguments, path, and risk.",
          x: 0.52,
          y: 0.3,
          type: "control",
        },
        {
          id: "policy",
          label: "Policy",
          detail: "Rules block missing order IDs, unsafe commands, or writes outside scope.",
          x: 0.52,
          y: 0.68,
          type: "review",
        },
        {
          id: "tool",
          label: "Write tool",
          detail: "Allowed actions continue; denied actions return a concrete reason.",
          x: 0.72,
          y: 0.5,
          type: "tool",
        },
        {
          id: "result",
          label: "Decision",
          detail: "The model sees the hook result and can choose a safer next step.",
          x: 0.94,
          y: 0.5,
          type: "state",
        },
      ],
      edges: [
        { from: "request", to: "agent", label: "task" },
        { from: "agent", to: "hook", label: "tool call" },
        { from: "hook", to: "policy", label: "check", bend: 72 },
        { from: "policy", to: "hook", label: "", bend: -72, dashed: true },
        { from: "hook", to: "tool", label: "allowed" },
        { from: "hook", to: "agent", label: "blocked", bend: -62, dashed: true },
        { from: "tool", to: "result", label: "", bend: -16 },
      ],
      metrics: [
        { label: "determinism", value: 0.9 },
        { label: "latency cost", value: 0.42 },
        { label: "coverage risk", value: 0.38 },
      ],
    },
    {
      id: "audit",
      label: "audit",
      caption: "Post-tool and stop hooks leave an audit trail without steering every model turn.",
      nodes: [
        {
          id: "tool",
          label: "Tool result",
          detail: "The refund tool returns an approval, denial, or policy error.",
          x: 0.12,
          y: 0.5,
          type: "tool",
        },
        {
          id: "post",
          label: "PostToolUse",
          detail: "The hook records what ran and can add context before the model continues.",
          x: 0.38,
          y: 0.3,
          type: "control",
        },
        {
          id: "ledger",
          label: "Ledger",
          detail: "A side effect writes compliance, debugging, or analytics data.",
          x: 0.62,
          y: 0.25,
          type: "state",
        },
        {
          id: "agent",
          label: "Agent",
          detail: "The model receives the original result plus hook-supplied context.",
          x: 0.62,
          y: 0.62,
          type: "worker",
        },
        {
          id: "stop",
          label: "Stop",
          detail: "End-of-turn hooks save state, notify humans, or close resources.",
          x: 0.86,
          y: 0.48,
          type: "review",
        },
      ],
      edges: [
        { from: "tool", to: "post", label: "result" },
        { from: "post", to: "ledger", label: "log" },
        { from: "post", to: "agent", label: "context" },
        { from: "agent", to: "stop", label: "turn done" },
        { from: "stop", to: "ledger", label: "final state", bend: -52, dashed: true },
      ],
      metrics: [
        { label: "observability", value: 0.86 },
        { label: "runtime control", value: 0.5 },
        { label: "side-effect risk", value: 0.58 },
      ],
    },
    {
      id: "memory",
      label: "memory",
      caption: "Prompt and compaction hooks can inject or preserve context at known boundaries.",
      nodes: [
        {
          id: "prompt",
          label: "Prompt",
          detail: "A new refund task enters the session.",
          x: 0.12,
          y: 0.5,
          type: "user",
        },
        {
          id: "submit",
          label: "Prompt hook",
          detail: "UserPromptSubmit adds relevant policy or project context.",
          x: 0.36,
          y: 0.31,
          type: "control",
        },
        {
          id: "memory",
          label: "Memory",
          detail: "Only targeted context should enter the prompt; broad recall becomes noise.",
          x: 0.58,
          y: 0.3,
          type: "state",
        },
        {
          id: "agent",
          label: "Agent turn",
          detail: "The model works with the user prompt plus hook-provided constraints.",
          x: 0.58,
          y: 0.66,
          type: "worker",
        },
        {
          id: "compact",
          label: "PreCompact",
          detail: "Before summarization, the hook can archive transcript or preserve evidence.",
          x: 0.86,
          y: 0.5,
          type: "review",
        },
      ],
      edges: [
        { from: "prompt", to: "submit", label: "submit" },
        { from: "submit", to: "memory", label: "retrieve" },
        { from: "memory", to: "agent", label: "add context" },
        { from: "submit", to: "agent", label: "continue" },
        { from: "agent", to: "compact", label: "long thread" },
        { from: "compact", to: "memory", label: "archive", bend: -60, dashed: true },
      ],
      metrics: [
        { label: "context fit", value: 0.74 },
        { label: "automation", value: 0.68 },
        { label: "noise risk", value: 0.54 },
      ],
    },
    {
      id: "overbroad",
      label: "overbroad",
      caption: "A broad matcher or slow hook turns deterministic control into ambient drag.",
      nodes: [
        {
          id: "every",
          label: "Every event",
          detail: "A matcher without scope runs for too many events and tools.",
          x: 0.12,
          y: 0.5,
          type: "user",
        },
        {
          id: "hook-a",
          label: "Hook A",
          detail: "One check blocks too much because it cannot distinguish arguments.",
          x: 0.38,
          y: 0.27,
          type: "control",
        },
        {
          id: "hook-b",
          label: "Hook B",
          detail: "Another hook logs the same event and adds latency.",
          x: 0.38,
          y: 0.68,
          type: "control",
        },
        {
          id: "queue",
          label: "Queue",
          detail: "Concurrent hooks can race; independent decisions must stand alone.",
          x: 0.62,
          y: 0.5,
          type: "review",
        },
        {
          id: "agent",
          label: "Agent",
          detail: "The model receives noisy context or unexplained denials.",
          x: 0.86,
          y: 0.5,
          type: "worker",
        },
      ],
      edges: [
        { from: "every", to: "hook-a", label: "all tools" },
        { from: "every", to: "hook-b", label: "all tools" },
        { from: "hook-a", to: "queue", label: "decision" },
        { from: "hook-b", to: "queue", label: "side effect" },
        { from: "queue", to: "agent", label: "drag" },
        { from: "agent", to: "hook-a", label: "retry", bend: 78, dashed: true },
      ],
      metrics: [
        { label: "determinism", value: 0.46 },
        { label: "latency cost", value: 0.84 },
        { label: "coverage risk", value: 0.72 },
      ],
    },
  ],
};

export function Hooks({ info }: { info?: ReactNode }) {
  return <AgentPatternCanvas config={config} info={info} />;
}
