// AUTO-GENERATED by scripts/build-embeddings.ts. Do not hand-edit.
// Regenerate with: pnpm build:embeddings
//
// Source model: Xenova/all-MiniLM-L6-v2 (quantized ONNX, 384D, unit-normalized).
// Projection: umap-js, seeded, with per-view parameters tuned for readability.
// Neighbors and analogies are computed in the full 384D space, not on UMAP
// coords — so drag-to-move in the UI cannot distort similarity scores.

export const CLUSTER_LABELS = [
  "animals",
  "actions",
  "emotions",
  "colors",
  "size",
  "food",
  "capitals",
  "countries",
] as const;

export const EMBEDDING_DIM = 384;
export const VOCAB_SIZE = 75;
export const EMBEDDING_MODEL = "Xenova/all-MiniLM-L6-v2";

export interface EmbeddingWord {
  word: string;
  cluster: number;
  baseX: number;
  baseY: number;
  neighbors: { idx: number; score: number }[];
}

export interface EmbeddingAnalogy {
  a: string;
  b: string;
  c: string;
  expected: string;
  label: string;
  top: { idx: number; score: number }[];
}

export interface EmbeddingDocumentChunk {
  id: string;
  title: string;
  source: string;
  category: string;
  text: string;
  baseX: number;
  baseY: number;
}

export interface EmbeddingSearchQuery {
  id: string;
  label: string;
  text: string;
  baseX: number;
  baseY: number;
  matches: { idx: number; score: number }[];
}

export interface EmbeddingContextualExample {
  word: string;
  note: string;
  anchors: { label: string; baseX: number; baseY: number }[];
  contexts: {
    label: string;
    phrase: string;
    baseX: number;
    baseY: number;
    nearestAnchors: { label: string; score: number }[];
  }[];
}

export const WORDS: EmbeddingWord[] = [
  {
    word: "cat",
    cluster: 0,
    baseX: 0.2229,
    baseY: 0.3173,
    neighbors: [
      {
        idx: 1,
        score: 0.6624,
      },
      {
        idx: 9,
        score: 0.5541,
      },
      {
        idx: 3,
        score: 0.5376,
      },
      {
        idx: 6,
        score: 0.5369,
      },
      {
        idx: 2,
        score: 0.5012,
      },
      {
        idx: 8,
        score: 0.4615,
      },
    ],
  },
  {
    word: "dog",
    cluster: 0,
    baseX: 0.2434,
    baseY: 0.345,
    neighbors: [
      {
        idx: 0,
        score: 0.6624,
      },
      {
        idx: 3,
        score: 0.5842,
      },
      {
        idx: 4,
        score: 0.537,
      },
      {
        idx: 9,
        score: 0.5205,
      },
      {
        idx: 6,
        score: 0.5051,
      },
      {
        idx: 7,
        score: 0.503,
      },
    ],
  },
  {
    word: "fish",
    cluster: 0,
    baseX: 0.2157,
    baseY: 0.2101,
    neighbors: [
      {
        idx: 11,
        score: 0.6152,
      },
      {
        idx: 56,
        score: 0.5714,
      },
      {
        idx: 3,
        score: 0.5076,
      },
      {
        idx: 15,
        score: 0.5027,
      },
      {
        idx: 0,
        score: 0.5012,
      },
      {
        idx: 4,
        score: 0.4878,
      },
    ],
  },
  {
    word: "bird",
    cluster: 0,
    baseX: 0.2591,
    baseY: 0.2686,
    neighbors: [
      {
        idx: 10,
        score: 0.6461,
      },
      {
        idx: 1,
        score: 0.5842,
      },
      {
        idx: 0,
        score: 0.5376,
      },
      {
        idx: 2,
        score: 0.5076,
      },
      {
        idx: 9,
        score: 0.5039,
      },
      {
        idx: 16,
        score: 0.5011,
      },
    ],
  },
  {
    word: "horse",
    cluster: 0,
    baseX: 0.2271,
    baseY: 0.2504,
    neighbors: [
      {
        idx: 1,
        score: 0.537,
      },
      {
        idx: 56,
        score: 0.4932,
      },
      {
        idx: 2,
        score: 0.4878,
      },
      {
        idx: 3,
        score: 0.4766,
      },
      {
        idx: 0,
        score: 0.4174,
      },
      {
        idx: 8,
        score: 0.3917,
      },
    ],
  },
  {
    word: "mouse",
    cluster: 0,
    baseX: 0.2877,
    baseY: 0.2898,
    neighbors: [
      {
        idx: 3,
        score: 0.417,
      },
      {
        idx: 16,
        score: 0.3918,
      },
      {
        idx: 0,
        score: 0.3875,
      },
      {
        idx: 6,
        score: 0.3779,
      },
      {
        idx: 1,
        score: 0.3633,
      },
      {
        idx: 41,
        score: 0.3611,
      },
    ],
  },
  {
    word: "lion",
    cluster: 0,
    baseX: 0.1693,
    baseY: 0.3281,
    neighbors: [
      {
        idx: 9,
        score: 0.6687,
      },
      {
        idx: 0,
        score: 0.5369,
      },
      {
        idx: 10,
        score: 0.5328,
      },
      {
        idx: 7,
        score: 0.5138,
      },
      {
        idx: 1,
        score: 0.5051,
      },
      {
        idx: 3,
        score: 0.4612,
      },
    ],
  },
  {
    word: "wolf",
    cluster: 0,
    baseX: 0.187,
    baseY: 0.3719,
    neighbors: [
      {
        idx: 6,
        score: 0.5138,
      },
      {
        idx: 8,
        score: 0.5059,
      },
      {
        idx: 1,
        score: 0.503,
      },
      {
        idx: 9,
        score: 0.4661,
      },
      {
        idx: 11,
        score: 0.4391,
      },
      {
        idx: 0,
        score: 0.4359,
      },
    ],
  },
  {
    word: "bear",
    cluster: 0,
    baseX: 0.2157,
    baseY: 0.3684,
    neighbors: [
      {
        idx: 7,
        score: 0.5059,
      },
      {
        idx: 1,
        score: 0.4893,
      },
      {
        idx: 0,
        score: 0.4615,
      },
      {
        idx: 3,
        score: 0.4429,
      },
      {
        idx: 10,
        score: 0.4286,
      },
      {
        idx: 49,
        score: 0.4281,
      },
    ],
  },
  {
    word: "tiger",
    cluster: 0,
    baseX: 0.1894,
    baseY: 0.3078,
    neighbors: [
      {
        idx: 6,
        score: 0.6687,
      },
      {
        idx: 0,
        score: 0.5541,
      },
      {
        idx: 11,
        score: 0.5321,
      },
      {
        idx: 1,
        score: 0.5205,
      },
      {
        idx: 3,
        score: 0.5039,
      },
      {
        idx: 10,
        score: 0.4795,
      },
    ],
  },
  {
    word: "eagle",
    cluster: 0,
    baseX: 0.2398,
    baseY: 0.2918,
    neighbors: [
      {
        idx: 3,
        score: 0.6461,
      },
      {
        idx: 6,
        score: 0.5328,
      },
      {
        idx: 9,
        score: 0.4795,
      },
      {
        idx: 8,
        score: 0.4286,
      },
      {
        idx: 41,
        score: 0.41,
      },
      {
        idx: 16,
        score: 0.405,
      },
    ],
  },
  {
    word: "shark",
    cluster: 0,
    baseX: 0.1828,
    baseY: 0.2507,
    neighbors: [
      {
        idx: 2,
        score: 0.6152,
      },
      {
        idx: 9,
        score: 0.5321,
      },
      {
        idx: 3,
        score: 0.4649,
      },
      {
        idx: 56,
        score: 0.4617,
      },
      {
        idx: 6,
        score: 0.4443,
      },
      {
        idx: 7,
        score: 0.4391,
      },
    ],
  },
  {
    word: "run",
    cluster: 1,
    baseX: 0.3148,
    baseY: 0.7346,
    neighbors: [
      {
        idx: 22,
        score: 0.8181,
      },
      {
        idx: 13,
        score: 0.4506,
      },
      {
        idx: 24,
        score: 0.419,
      },
      {
        idx: 23,
        score: 0.418,
      },
      {
        idx: 14,
        score: 0.4179,
      },
      {
        idx: 15,
        score: 0.4044,
      },
    ],
  },
  {
    word: "walk",
    cluster: 1,
    baseX: 0.282,
    baseY: 0.7681,
    neighbors: [
      {
        idx: 23,
        score: 0.8615,
      },
      {
        idx: 20,
        score: 0.5291,
      },
      {
        idx: 17,
        score: 0.4929,
      },
      {
        idx: 14,
        score: 0.4663,
      },
      {
        idx: 12,
        score: 0.4506,
      },
      {
        idx: 24,
        score: 0.4014,
      },
    ],
  },
  {
    word: "jump",
    cluster: 1,
    baseX: 0.25,
    baseY: 0.7071,
    neighbors: [
      {
        idx: 24,
        score: 0.8681,
      },
      {
        idx: 19,
        score: 0.7379,
      },
      {
        idx: 16,
        score: 0.5664,
      },
      {
        idx: 17,
        score: 0.5294,
      },
      {
        idx: 15,
        score: 0.4982,
      },
      {
        idx: 13,
        score: 0.4663,
      },
    ],
  },
  {
    word: "swim",
    cluster: 1,
    baseX: 0.2125,
    baseY: 0.7036,
    neighbors: [
      {
        idx: 2,
        score: 0.5027,
      },
      {
        idx: 14,
        score: 0.4982,
      },
      {
        idx: 24,
        score: 0.4569,
      },
      {
        idx: 11,
        score: 0.4384,
      },
      {
        idx: 16,
        score: 0.4332,
      },
      {
        idx: 17,
        score: 0.4121,
      },
    ],
  },
  {
    word: "fly",
    cluster: 1,
    baseX: 0.2036,
    baseY: 0.6724,
    neighbors: [
      {
        idx: 14,
        score: 0.5664,
      },
      {
        idx: 19,
        score: 0.5062,
      },
      {
        idx: 24,
        score: 0.5011,
      },
      {
        idx: 3,
        score: 0.5011,
      },
      {
        idx: 15,
        score: 0.4332,
      },
      {
        idx: 58,
        score: 0.4303,
      },
    ],
  },
  {
    word: "climb",
    cluster: 1,
    baseX: 0.2602,
    baseY: 0.751,
    neighbors: [
      {
        idx: 14,
        score: 0.5294,
      },
      {
        idx: 24,
        score: 0.4976,
      },
      {
        idx: 13,
        score: 0.4929,
      },
      {
        idx: 20,
        score: 0.4902,
      },
      {
        idx: 23,
        score: 0.4473,
      },
      {
        idx: 15,
        score: 0.4121,
      },
    ],
  },
  {
    word: "sprint",
    cluster: 1,
    baseX: 0.3365,
    baseY: 0.6842,
    neighbors: [
      {
        idx: 21,
        score: 0.3997,
      },
      {
        idx: 22,
        score: 0.3787,
      },
      {
        idx: 12,
        score: 0.3581,
      },
      {
        idx: 68,
        score: 0.3189,
      },
      {
        idx: 56,
        score: 0.3173,
      },
      {
        idx: 14,
        score: 0.3147,
      },
    ],
  },
  {
    word: "leap",
    cluster: 1,
    baseX: 0.2704,
    baseY: 0.682,
    neighbors: [
      {
        idx: 14,
        score: 0.7379,
      },
      {
        idx: 24,
        score: 0.6525,
      },
      {
        idx: 16,
        score: 0.5062,
      },
      {
        idx: 17,
        score: 0.404,
      },
      {
        idx: 13,
        score: 0.389,
      },
      {
        idx: 21,
        score: 0.3808,
      },
    ],
  },
  {
    word: "crawl",
    cluster: 1,
    baseX: 0.2646,
    baseY: 0.7917,
    neighbors: [
      {
        idx: 13,
        score: 0.5291,
      },
      {
        idx: 17,
        score: 0.4902,
      },
      {
        idx: 23,
        score: 0.4623,
      },
      {
        idx: 7,
        score: 0.4119,
      },
      {
        idx: 12,
        score: 0.3714,
      },
      {
        idx: 0,
        score: 0.3709,
      },
    ],
  },
  {
    word: "dash",
    cluster: 1,
    baseX: 0.3184,
    baseY: 0.6704,
    neighbors: [
      {
        idx: 22,
        score: 0.4138,
      },
      {
        idx: 18,
        score: 0.3997,
      },
      {
        idx: 14,
        score: 0.3933,
      },
      {
        idx: 41,
        score: 0.3875,
      },
      {
        idx: 6,
        score: 0.3827,
      },
      {
        idx: 19,
        score: 0.3808,
      },
    ],
  },
  {
    word: "ran",
    cluster: 1,
    baseX: 0.3393,
    baseY: 0.715,
    neighbors: [
      {
        idx: 12,
        score: 0.8181,
      },
      {
        idx: 24,
        score: 0.4631,
      },
      {
        idx: 23,
        score: 0.4276,
      },
      {
        idx: 21,
        score: 0.4138,
      },
      {
        idx: 42,
        score: 0.4044,
      },
      {
        idx: 29,
        score: 0.3947,
      },
    ],
  },
  {
    word: "walked",
    cluster: 1,
    baseX: 0.3105,
    baseY: 0.7614,
    neighbors: [
      {
        idx: 13,
        score: 0.8615,
      },
      {
        idx: 24,
        score: 0.5075,
      },
      {
        idx: 20,
        score: 0.4623,
      },
      {
        idx: 17,
        score: 0.4473,
      },
      {
        idx: 14,
        score: 0.4416,
      },
      {
        idx: 22,
        score: 0.4276,
      },
    ],
  },
  {
    word: "jumped",
    cluster: 1,
    baseX: 0.2772,
    baseY: 0.7184,
    neighbors: [
      {
        idx: 14,
        score: 0.8681,
      },
      {
        idx: 19,
        score: 0.6525,
      },
      {
        idx: 23,
        score: 0.5075,
      },
      {
        idx: 16,
        score: 0.5011,
      },
      {
        idx: 17,
        score: 0.4976,
      },
      {
        idx: 22,
        score: 0.4631,
      },
    ],
  },
  {
    word: "happy",
    cluster: 2,
    baseX: 0.5173,
    baseY: 0.2922,
    neighbors: [
      {
        idx: 29,
        score: 0.5802,
      },
      {
        idx: 31,
        score: 0.5334,
      },
      {
        idx: 27,
        score: 0.4228,
      },
      {
        idx: 26,
        score: 0.3854,
      },
      {
        idx: 45,
        score: 0.3754,
      },
      {
        idx: 28,
        score: 0.373,
      },
    ],
  },
  {
    word: "sad",
    cluster: 2,
    baseX: 0.4526,
    baseY: 0.2678,
    neighbors: [
      {
        idx: 25,
        score: 0.3854,
      },
      {
        idx: 27,
        score: 0.3344,
      },
      {
        idx: 31,
        score: 0.295,
      },
      {
        idx: 45,
        score: 0.2774,
      },
      {
        idx: 47,
        score: 0.2769,
      },
      {
        idx: 32,
        score: 0.2704,
      },
    ],
  },
  {
    word: "angry",
    cluster: 2,
    baseX: 0.5445,
    baseY: 0.2269,
    neighbors: [
      {
        idx: 28,
        score: 0.5389,
      },
      {
        idx: 30,
        score: 0.4821,
      },
      {
        idx: 29,
        score: 0.4583,
      },
      {
        idx: 41,
        score: 0.439,
      },
      {
        idx: 25,
        score: 0.4228,
      },
      {
        idx: 58,
        score: 0.412,
      },
    ],
  },
  {
    word: "calm",
    cluster: 2,
    baseX: 0.5453,
    baseY: 0.1712,
    neighbors: [
      {
        idx: 27,
        score: 0.5389,
      },
      {
        idx: 34,
        score: 0.4938,
      },
      {
        idx: 30,
        score: 0.4595,
      },
      {
        idx: 29,
        score: 0.4281,
      },
      {
        idx: 33,
        score: 0.4228,
      },
      {
        idx: 44,
        score: 0.3954,
      },
    ],
  },
  {
    word: "excited",
    cluster: 2,
    baseX: 0.5529,
    baseY: 0.2749,
    neighbors: [
      {
        idx: 25,
        score: 0.5802,
      },
      {
        idx: 27,
        score: 0.4583,
      },
      {
        idx: 28,
        score: 0.4281,
      },
      {
        idx: 45,
        score: 0.425,
      },
      {
        idx: 31,
        score: 0.3988,
      },
      {
        idx: 35,
        score: 0.3975,
      },
    ],
  },
  {
    word: "fearful",
    cluster: 2,
    baseX: 0.5152,
    baseY: 0.1901,
    neighbors: [
      {
        idx: 27,
        score: 0.4821,
      },
      {
        idx: 28,
        score: 0.4595,
      },
      {
        idx: 33,
        score: 0.4451,
      },
      {
        idx: 32,
        score: 0.4149,
      },
      {
        idx: 29,
        score: 0.392,
      },
      {
        idx: 34,
        score: 0.3916,
      },
    ],
  },
  {
    word: "proud",
    cluster: 2,
    baseX: 0.4919,
    baseY: 0.2757,
    neighbors: [
      {
        idx: 25,
        score: 0.5334,
      },
      {
        idx: 33,
        score: 0.4609,
      },
      {
        idx: 29,
        score: 0.3988,
      },
      {
        idx: 45,
        score: 0.3817,
      },
      {
        idx: 27,
        score: 0.365,
      },
      {
        idx: 58,
        score: 0.3441,
      },
    ],
  },
  {
    word: "shy",
    cluster: 2,
    baseX: 0.4496,
    baseY: 0.1746,
    neighbors: [
      {
        idx: 33,
        score: 0.4442,
      },
      {
        idx: 30,
        score: 0.4149,
      },
      {
        idx: 34,
        score: 0.404,
      },
      {
        idx: 28,
        score: 0.3737,
      },
      {
        idx: 23,
        score: 0.3728,
      },
      {
        idx: 52,
        score: 0.3628,
      },
    ],
  },
  {
    word: "brave",
    cluster: 2,
    baseX: 0.466,
    baseY: 0.1894,
    neighbors: [
      {
        idx: 31,
        score: 0.4609,
      },
      {
        idx: 30,
        score: 0.4451,
      },
      {
        idx: 32,
        score: 0.4442,
      },
      {
        idx: 34,
        score: 0.4411,
      },
      {
        idx: 28,
        score: 0.4228,
      },
      {
        idx: 27,
        score: 0.3937,
      },
    ],
  },
  {
    word: "gentle",
    cluster: 2,
    baseX: 0.4646,
    baseY: 0.1373,
    neighbors: [
      {
        idx: 28,
        score: 0.4938,
      },
      {
        idx: 52,
        score: 0.4736,
      },
      {
        idx: 33,
        score: 0.4411,
      },
      {
        idx: 32,
        score: 0.404,
      },
      {
        idx: 30,
        score: 0.3916,
      },
      {
        idx: 47,
        score: 0.3538,
      },
    ],
  },
  {
    word: "red",
    cluster: 3,
    baseX: 0.445,
    baseY: 0.8138,
    neighbors: [
      {
        idx: 36,
        score: 0.7191,
      },
      {
        idx: 37,
        score: 0.6909,
      },
      {
        idx: 38,
        score: 0.679,
      },
      {
        idx: 39,
        score: 0.6649,
      },
      {
        idx: 43,
        score: 0.6623,
      },
      {
        idx: 40,
        score: 0.6508,
      },
    ],
  },
  {
    word: "blue",
    cluster: 3,
    baseX: 0.5078,
    baseY: 0.7912,
    neighbors: [
      {
        idx: 39,
        score: 0.7401,
      },
      {
        idx: 35,
        score: 0.7191,
      },
      {
        idx: 37,
        score: 0.6803,
      },
      {
        idx: 44,
        score: 0.6759,
      },
      {
        idx: 41,
        score: 0.6641,
      },
      {
        idx: 38,
        score: 0.6548,
      },
    ],
  },
  {
    word: "green",
    cluster: 3,
    baseX: 0.4746,
    baseY: 0.7956,
    neighbors: [
      {
        idx: 35,
        score: 0.6909,
      },
      {
        idx: 36,
        score: 0.6803,
      },
      {
        idx: 39,
        score: 0.6581,
      },
      {
        idx: 44,
        score: 0.6563,
      },
      {
        idx: 38,
        score: 0.653,
      },
      {
        idx: 40,
        score: 0.6488,
      },
    ],
  },
  {
    word: "yellow",
    cluster: 3,
    baseX: 0.4482,
    baseY: 0.7676,
    neighbors: [
      {
        idx: 35,
        score: 0.679,
      },
      {
        idx: 42,
        score: 0.6703,
      },
      {
        idx: 36,
        score: 0.6548,
      },
      {
        idx: 40,
        score: 0.6531,
      },
      {
        idx: 37,
        score: 0.653,
      },
      {
        idx: 44,
        score: 0.6082,
      },
    ],
  },
  {
    word: "purple",
    cluster: 3,
    baseX: 0.4957,
    baseY: 0.8416,
    neighbors: [
      {
        idx: 36,
        score: 0.7401,
      },
      {
        idx: 43,
        score: 0.7193,
      },
      {
        idx: 40,
        score: 0.6725,
      },
      {
        idx: 35,
        score: 0.6649,
      },
      {
        idx: 41,
        score: 0.6598,
      },
      {
        idx: 37,
        score: 0.6581,
      },
    ],
  },
  {
    word: "orange",
    cluster: 3,
    baseX: 0.4434,
    baseY: 0.87,
    neighbors: [
      {
        idx: 39,
        score: 0.6725,
      },
      {
        idx: 38,
        score: 0.6531,
      },
      {
        idx: 35,
        score: 0.6508,
      },
      {
        idx: 37,
        score: 0.6488,
      },
      {
        idx: 43,
        score: 0.6197,
      },
      {
        idx: 57,
        score: 0.6177,
      },
    ],
  },
  {
    word: "black",
    cluster: 3,
    baseX: 0.5705,
    baseY: 0.7997,
    neighbors: [
      {
        idx: 42,
        score: 0.7566,
      },
      {
        idx: 44,
        score: 0.7017,
      },
      {
        idx: 36,
        score: 0.6641,
      },
      {
        idx: 39,
        score: 0.6598,
      },
      {
        idx: 43,
        score: 0.6468,
      },
      {
        idx: 35,
        score: 0.6364,
      },
    ],
  },
  {
    word: "white",
    cluster: 3,
    baseX: 0.5232,
    baseY: 0.7288,
    neighbors: [
      {
        idx: 41,
        score: 0.7566,
      },
      {
        idx: 44,
        score: 0.6952,
      },
      {
        idx: 38,
        score: 0.6703,
      },
      {
        idx: 36,
        score: 0.6307,
      },
      {
        idx: 37,
        score: 0.6303,
      },
      {
        idx: 43,
        score: 0.6226,
      },
    ],
  },
  {
    word: "pink",
    cluster: 3,
    baseX: 0.5328,
    baseY: 0.8433,
    neighbors: [
      {
        idx: 39,
        score: 0.7193,
      },
      {
        idx: 35,
        score: 0.6623,
      },
      {
        idx: 41,
        score: 0.6468,
      },
      {
        idx: 36,
        score: 0.6442,
      },
      {
        idx: 37,
        score: 0.6327,
      },
      {
        idx: 42,
        score: 0.6226,
      },
    ],
  },
  {
    word: "gray",
    cluster: 3,
    baseX: 0.5588,
    baseY: 0.7483,
    neighbors: [
      {
        idx: 41,
        score: 0.7017,
      },
      {
        idx: 42,
        score: 0.6952,
      },
      {
        idx: 36,
        score: 0.6759,
      },
      {
        idx: 37,
        score: 0.6563,
      },
      {
        idx: 39,
        score: 0.6374,
      },
      {
        idx: 35,
        score: 0.6251,
      },
    ],
  },
  {
    word: "big",
    cluster: 4,
    baseX: 0.728,
    baseY: 0.335,
    neighbors: [
      {
        idx: 48,
        score: 0.878,
      },
      {
        idx: 50,
        score: 0.7844,
      },
      {
        idx: 53,
        score: 0.7229,
      },
      {
        idx: 47,
        score: 0.6578,
      },
      {
        idx: 46,
        score: 0.6493,
      },
      {
        idx: 49,
        score: 0.6011,
      },
    ],
  },
  {
    word: "small",
    cluster: 4,
    baseX: 0.744,
    baseY: 0.2705,
    neighbors: [
      {
        idx: 47,
        score: 0.9096,
      },
      {
        idx: 50,
        score: 0.7768,
      },
      {
        idx: 52,
        score: 0.7352,
      },
      {
        idx: 45,
        score: 0.6493,
      },
      {
        idx: 48,
        score: 0.6481,
      },
      {
        idx: 53,
        score: 0.6268,
      },
    ],
  },
  {
    word: "tiny",
    cluster: 4,
    baseX: 0.7624,
    baseY: 0.3021,
    neighbors: [
      {
        idx: 46,
        score: 0.9096,
      },
      {
        idx: 52,
        score: 0.7779,
      },
      {
        idx: 50,
        score: 0.693,
      },
      {
        idx: 45,
        score: 0.6578,
      },
      {
        idx: 48,
        score: 0.6475,
      },
      {
        idx: 53,
        score: 0.6225,
      },
    ],
  },
  {
    word: "huge",
    cluster: 4,
    baseX: 0.6901,
    baseY: 0.3408,
    neighbors: [
      {
        idx: 45,
        score: 0.878,
      },
      {
        idx: 53,
        score: 0.8182,
      },
      {
        idx: 50,
        score: 0.8135,
      },
      {
        idx: 49,
        score: 0.6712,
      },
      {
        idx: 46,
        score: 0.6481,
      },
      {
        idx: 47,
        score: 0.6475,
      },
    ],
  },
  {
    word: "giant",
    cluster: 4,
    baseX: 0.7133,
    baseY: 0.2909,
    neighbors: [
      {
        idx: 53,
        score: 0.6965,
      },
      {
        idx: 50,
        score: 0.6794,
      },
      {
        idx: 48,
        score: 0.6712,
      },
      {
        idx: 45,
        score: 0.6011,
      },
      {
        idx: 46,
        score: 0.5972,
      },
      {
        idx: 51,
        score: 0.5837,
      },
    ],
  },
  {
    word: "large",
    cluster: 4,
    baseX: 0.678,
    baseY: 0.3075,
    neighbors: [
      {
        idx: 48,
        score: 0.8135,
      },
      {
        idx: 45,
        score: 0.7844,
      },
      {
        idx: 46,
        score: 0.7768,
      },
      {
        idx: 53,
        score: 0.7633,
      },
      {
        idx: 47,
        score: 0.693,
      },
      {
        idx: 49,
        score: 0.6794,
      },
    ],
  },
  {
    word: "vast",
    cluster: 4,
    baseX: 0.6658,
    baseY: 0.2835,
    neighbors: [
      {
        idx: 50,
        score: 0.6399,
      },
      {
        idx: 53,
        score: 0.6368,
      },
      {
        idx: 48,
        score: 0.5976,
      },
      {
        idx: 49,
        score: 0.5837,
      },
      {
        idx: 46,
        score: 0.5333,
      },
      {
        idx: 47,
        score: 0.5245,
      },
    ],
  },
  {
    word: "little",
    cluster: 4,
    baseX: 0.81,
    baseY: 0.302,
    neighbors: [
      {
        idx: 47,
        score: 0.7779,
      },
      {
        idx: 46,
        score: 0.7352,
      },
      {
        idx: 34,
        score: 0.4736,
      },
      {
        idx: 45,
        score: 0.4564,
      },
      {
        idx: 50,
        score: 0.4246,
      },
      {
        idx: 49,
        score: 0.4183,
      },
    ],
  },
  {
    word: "massive",
    cluster: 4,
    baseX: 0.6884,
    baseY: 0.2677,
    neighbors: [
      {
        idx: 48,
        score: 0.8182,
      },
      {
        idx: 50,
        score: 0.7633,
      },
      {
        idx: 45,
        score: 0.7229,
      },
      {
        idx: 49,
        score: 0.6965,
      },
      {
        idx: 51,
        score: 0.6368,
      },
      {
        idx: 46,
        score: 0.6268,
      },
    ],
  },
  {
    word: "bread",
    cluster: 5,
    baseX: 0.6497,
    baseY: 0.7029,
    neighbors: [
      {
        idx: 62,
        score: 0.5446,
      },
      {
        idx: 56,
        score: 0.5063,
      },
      {
        idx: 55,
        score: 0.4829,
      },
      {
        idx: 58,
        score: 0.4779,
      },
      {
        idx: 60,
        score: 0.4586,
      },
      {
        idx: 57,
        score: 0.4586,
      },
    ],
  },
  {
    word: "rice",
    cluster: 5,
    baseX: 0.6886,
    baseY: 0.6634,
    neighbors: [
      {
        idx: 57,
        score: 0.5038,
      },
      {
        idx: 60,
        score: 0.4972,
      },
      {
        idx: 54,
        score: 0.4829,
      },
      {
        idx: 61,
        score: 0.4766,
      },
      {
        idx: 56,
        score: 0.4563,
      },
      {
        idx: 62,
        score: 0.4506,
      },
    ],
  },
  {
    word: "meat",
    cluster: 5,
    baseX: 0.731,
    baseY: 0.8045,
    neighbors: [
      {
        idx: 2,
        score: 0.5714,
      },
      {
        idx: 62,
        score: 0.5657,
      },
      {
        idx: 59,
        score: 0.5153,
      },
      {
        idx: 54,
        score: 0.5063,
      },
      {
        idx: 57,
        score: 0.5062,
      },
      {
        idx: 4,
        score: 0.4932,
      },
    ],
  },
  {
    word: "fruit",
    cluster: 5,
    baseX: 0.7387,
    baseY: 0.653,
    neighbors: [
      {
        idx: 40,
        score: 0.6177,
      },
      {
        idx: 61,
        score: 0.5492,
      },
      {
        idx: 56,
        score: 0.5062,
      },
      {
        idx: 55,
        score: 0.5038,
      },
      {
        idx: 37,
        score: 0.4943,
      },
      {
        idx: 62,
        score: 0.4817,
      },
    ],
  },
  {
    word: "cake",
    cluster: 5,
    baseX: 0.6398,
    baseY: 0.7382,
    neighbors: [
      {
        idx: 54,
        score: 0.4779,
      },
      {
        idx: 62,
        score: 0.4522,
      },
      {
        idx: 1,
        score: 0.444,
      },
      {
        idx: 60,
        score: 0.4309,
      },
      {
        idx: 16,
        score: 0.4303,
      },
      {
        idx: 57,
        score: 0.4289,
      },
    ],
  },
  {
    word: "soup",
    cluster: 5,
    baseX: 0.7439,
    baseY: 0.7437,
    neighbors: [
      {
        idx: 61,
        score: 0.5744,
      },
      {
        idx: 60,
        score: 0.5717,
      },
      {
        idx: 56,
        score: 0.5153,
      },
      {
        idx: 62,
        score: 0.4841,
      },
      {
        idx: 57,
        score: 0.4126,
      },
      {
        idx: 40,
        score: 0.3928,
      },
    ],
  },
  {
    word: "pasta",
    cluster: 5,
    baseX: 0.6904,
    baseY: 0.7156,
    neighbors: [
      {
        idx: 62,
        score: 0.6398,
      },
      {
        idx: 59,
        score: 0.5717,
      },
      {
        idx: 61,
        score: 0.5362,
      },
      {
        idx: 55,
        score: 0.4972,
      },
      {
        idx: 56,
        score: 0.4929,
      },
      {
        idx: 54,
        score: 0.4586,
      },
    ],
  },
  {
    word: "salad",
    cluster: 5,
    baseX: 0.7251,
    baseY: 0.7019,
    neighbors: [
      {
        idx: 59,
        score: 0.5744,
      },
      {
        idx: 62,
        score: 0.5547,
      },
      {
        idx: 57,
        score: 0.5492,
      },
      {
        idx: 60,
        score: 0.5362,
      },
      {
        idx: 56,
        score: 0.4903,
      },
      {
        idx: 55,
        score: 0.4766,
      },
    ],
  },
  {
    word: "cheese",
    cluster: 5,
    baseX: 0.6927,
    baseY: 0.7569,
    neighbors: [
      {
        idx: 60,
        score: 0.6398,
      },
      {
        idx: 56,
        score: 0.5657,
      },
      {
        idx: 61,
        score: 0.5547,
      },
      {
        idx: 54,
        score: 0.5446,
      },
      {
        idx: 59,
        score: 0.4841,
      },
      {
        idx: 57,
        score: 0.4817,
      },
    ],
  },
  {
    word: "paris",
    cluster: 6,
    baseX: 0.851,
    baseY: 0.2675,
    neighbors: [
      {
        idx: 69,
        score: 0.7393,
      },
      {
        idx: 66,
        score: 0.5842,
      },
      {
        idx: 64,
        score: 0.5697,
      },
      {
        idx: 67,
        score: 0.5563,
      },
      {
        idx: 65,
        score: 0.5102,
      },
      {
        idx: 70,
        score: 0.5048,
      },
    ],
  },
  {
    word: "berlin",
    cluster: 6,
    baseX: 0.8103,
    baseY: 0.2829,
    neighbors: [
      {
        idx: 70,
        score: 0.7021,
      },
      {
        idx: 66,
        score: 0.5889,
      },
      {
        idx: 65,
        score: 0.5843,
      },
      {
        idx: 63,
        score: 0.5697,
      },
      {
        idx: 67,
        score: 0.5388,
      },
      {
        idx: 69,
        score: 0.4955,
      },
    ],
  },
  {
    word: "tokyo",
    cluster: 6,
    baseX: 0.88,
    baseY: 0.2979,
    neighbors: [
      {
        idx: 71,
        score: 0.7623,
      },
      {
        idx: 64,
        score: 0.5843,
      },
      {
        idx: 67,
        score: 0.5174,
      },
      {
        idx: 63,
        score: 0.5102,
      },
      {
        idx: 70,
        score: 0.4781,
      },
      {
        idx: 66,
        score: 0.4753,
      },
    ],
  },
  {
    word: "london",
    cluster: 6,
    baseX: 0.7818,
    baseY: 0.2477,
    neighbors: [
      {
        idx: 72,
        score: 0.5931,
      },
      {
        idx: 64,
        score: 0.5889,
      },
      {
        idx: 63,
        score: 0.5842,
      },
      {
        idx: 70,
        score: 0.4874,
      },
      {
        idx: 65,
        score: 0.4753,
      },
      {
        idx: 68,
        score: 0.4506,
      },
    ],
  },
  {
    word: "rome",
    cluster: 6,
    baseX: 0.925,
    baseY: 0.244,
    neighbors: [
      {
        idx: 73,
        score: 0.6621,
      },
      {
        idx: 63,
        score: 0.5563,
      },
      {
        idx: 69,
        score: 0.5446,
      },
      {
        idx: 64,
        score: 0.5388,
      },
      {
        idx: 74,
        score: 0.5327,
      },
      {
        idx: 65,
        score: 0.5174,
      },
    ],
  },
  {
    word: "madrid",
    cluster: 6,
    baseX: 0.8519,
    baseY: 0.16,
    neighbors: [
      {
        idx: 74,
        score: 0.7357,
      },
      {
        idx: 73,
        score: 0.5778,
      },
      {
        idx: 69,
        score: 0.544,
      },
      {
        idx: 72,
        score: 0.5383,
      },
      {
        idx: 70,
        score: 0.5299,
      },
      {
        idx: 64,
        score: 0.4668,
      },
    ],
  },
  {
    word: "france",
    cluster: 7,
    baseX: 0.8191,
    baseY: 0.6791,
    neighbors: [
      {
        idx: 70,
        score: 0.7472,
      },
      {
        idx: 63,
        score: 0.7393,
      },
      {
        idx: 73,
        score: 0.7246,
      },
      {
        idx: 74,
        score: 0.7052,
      },
      {
        idx: 72,
        score: 0.6959,
      },
      {
        idx: 71,
        score: 0.5588,
      },
    ],
  },
  {
    word: "germany",
    cluster: 7,
    baseX: 0.7864,
    baseY: 0.7534,
    neighbors: [
      {
        idx: 72,
        score: 0.7797,
      },
      {
        idx: 73,
        score: 0.7599,
      },
      {
        idx: 69,
        score: 0.7472,
      },
      {
        idx: 64,
        score: 0.7021,
      },
      {
        idx: 71,
        score: 0.6902,
      },
      {
        idx: 74,
        score: 0.6728,
      },
    ],
  },
  {
    word: "japan",
    cluster: 7,
    baseX: 0.8831,
    baseY: 0.8337,
    neighbors: [
      {
        idx: 65,
        score: 0.7623,
      },
      {
        idx: 70,
        score: 0.6902,
      },
      {
        idx: 73,
        score: 0.6714,
      },
      {
        idx: 72,
        score: 0.596,
      },
      {
        idx: 74,
        score: 0.5644,
      },
      {
        idx: 69,
        score: 0.5588,
      },
    ],
  },
  {
    word: "england",
    cluster: 7,
    baseX: 0.8255,
    baseY: 0.7877,
    neighbors: [
      {
        idx: 70,
        score: 0.7797,
      },
      {
        idx: 73,
        score: 0.7011,
      },
      {
        idx: 69,
        score: 0.6959,
      },
      {
        idx: 74,
        score: 0.6385,
      },
      {
        idx: 71,
        score: 0.596,
      },
      {
        idx: 66,
        score: 0.5931,
      },
    ],
  },
  {
    word: "italy",
    cluster: 7,
    baseX: 0.8986,
    baseY: 0.752,
    neighbors: [
      {
        idx: 70,
        score: 0.7599,
      },
      {
        idx: 69,
        score: 0.7246,
      },
      {
        idx: 72,
        score: 0.7011,
      },
      {
        idx: 74,
        score: 0.6985,
      },
      {
        idx: 71,
        score: 0.6714,
      },
      {
        idx: 67,
        score: 0.6621,
      },
    ],
  },
  {
    word: "spain",
    cluster: 7,
    baseX: 0.8873,
    baseY: 0.6941,
    neighbors: [
      {
        idx: 68,
        score: 0.7357,
      },
      {
        idx: 69,
        score: 0.7052,
      },
      {
        idx: 73,
        score: 0.6985,
      },
      {
        idx: 70,
        score: 0.6728,
      },
      {
        idx: 72,
        score: 0.6385,
      },
      {
        idx: 71,
        score: 0.5644,
      },
    ],
  },
];

export const ANALOGIES: EmbeddingAnalogy[] = [
  {
    a: "paris",
    b: "france",
    c: "germany",
    expected: "berlin",
    label: "paris − france + germany ≈ berlin",
    top: [
      {
        idx: 64,
        score: 0.7625,
      },
      {
        idx: 65,
        score: 0.6384,
      },
      {
        idx: 66,
        score: 0.6147,
      },
    ],
  },
  {
    a: "tokyo",
    b: "japan",
    c: "italy",
    expected: "rome",
    label: "tokyo − japan + italy ≈ rome",
    top: [
      {
        idx: 67,
        score: 0.6595,
      },
      {
        idx: 63,
        score: 0.5999,
      },
      {
        idx: 64,
        score: 0.5939,
      },
    ],
  },
  {
    a: "walk",
    b: "walked",
    c: "ran",
    expected: "run",
    label: "walk − walked + ran ≈ run",
    top: [
      {
        idx: 12,
        score: 0.8096,
      },
      {
        idx: 21,
        score: 0.404,
      },
      {
        idx: 18,
        score: 0.3669,
      },
    ],
  },
];

export const DOCUMENT_CHUNKS: EmbeddingDocumentChunk[] = [
  {
    id: "lion-speed",
    title: "Lion sprint speed",
    source: "field notes",
    category: "animals",
    text: "A lion can sprint quickly for short bursts when chasing prey across open grassland.",
    baseX: 0.1,
    baseY: 0.1546,
  },
  {
    id: "tiger-stalk",
    title: "Tiger ambush",
    source: "field notes",
    category: "animals",
    text: "Tigers rely on stealth, dense cover, and sudden acceleration rather than long pursuit.",
    baseX: 0.1407,
    baseY: 0.239,
  },
  {
    id: "horse-endurance",
    title: "Horse endurance",
    source: "field notes",
    category: "animals",
    text: "Horses are large animals built for distance running and carrying riders over terrain.",
    baseX: 0.1698,
    baseY: 0.12,
  },
  {
    id: "berlin-capital",
    title: "Berlin",
    source: "atlas",
    category: "cities",
    text: "Berlin is the capital city of Germany and a major center for art and technology.",
    baseX: 0.7254,
    baseY: 0.8066,
  },
  {
    id: "tokyo-rail",
    title: "Tokyo rail",
    source: "atlas",
    category: "cities",
    text: "Tokyo is Japan's capital and is known for dense neighborhoods and an enormous train network.",
    baseX: 0.6899,
    baseY: 0.88,
  },
  {
    id: "paris-france",
    title: "Paris",
    source: "atlas",
    category: "cities",
    text: "Paris is the capital of France, with landmarks, museums, and historic boulevards.",
    baseX: 0.7624,
    baseY: 0.8582,
  },
  {
    id: "bread-fermentation",
    title: "Bread fermentation",
    source: "cookbook",
    category: "food",
    text: "Bread dough develops flavor as yeast ferments sugars and produces gas before baking.",
    baseX: 0.5811,
    baseY: 0.5321,
  },
  {
    id: "pasta-sauce",
    title: "Pasta sauce",
    source: "cookbook",
    category: "food",
    text: "Pasta is often paired with tomato, cheese, herbs, and olive oil in quick meals.",
    baseX: 0.4867,
    baseY: 0.5533,
  },
  {
    id: "hnsw-index",
    title: "HNSW index",
    source: "engineering",
    category: "ml",
    text: "HNSW builds a layered nearest-neighbor graph so vector databases can search embeddings quickly.",
    baseX: 0.3425,
    baseY: 0.5564,
  },
  {
    id: "rag-context",
    title: "RAG context",
    source: "engineering",
    category: "ml",
    text: "Retrieval augmented generation embeds a user query, fetches relevant chunks, and sends them to a language model.",
    baseX: 0.4011,
    baseY: 0.6054,
  },
  {
    id: "river-bank",
    title: "River bank",
    source: "glossary",
    category: "geography",
    text: "A river bank is the sloped edge of land beside flowing water.",
    baseX: 0.8359,
    baseY: 0.6322,
  },
  {
    id: "savings-bank",
    title: "Savings bank",
    source: "glossary",
    category: "finance",
    text: "A bank can hold deposits, approve loans, and move money between accounts.",
    baseX: 0.9,
    baseY: 0.6669,
  },
];

export const SEARCH_QUERIES: EmbeddingSearchQuery[] = [
  {
    id: "fast-animal",
    label: "fast animal",
    text: "fast animal chasing prey",
    baseX: 0.2017,
    baseY: 0.2086,
    matches: [
      {
        idx: 0,
        score: 0.5585,
      },
      {
        idx: 1,
        score: 0.5284,
      },
      {
        idx: 2,
        score: 0.3771,
      },
      {
        idx: 8,
        score: 0.1012,
      },
      {
        idx: 7,
        score: 0.0961,
      },
      {
        idx: 10,
        score: 0.0864,
      },
      {
        idx: 11,
        score: 0.083,
      },
      {
        idx: 9,
        score: 0.0315,
      },
      {
        idx: 4,
        score: 0.0068,
      },
      {
        idx: 5,
        score: -0.0038,
      },
      {
        idx: 3,
        score: -0.0339,
      },
      {
        idx: 6,
        score: -0.0485,
      },
    ],
  },
  {
    id: "germany-capital",
    label: "capital of germany",
    text: "capital city of Germany",
    baseX: 0.6796,
    baseY: 0.7553,
    matches: [
      {
        idx: 3,
        score: 0.6308,
      },
      {
        idx: 5,
        score: 0.4343,
      },
      {
        idx: 4,
        score: 0.3346,
      },
      {
        idx: 10,
        score: 0.1026,
      },
      {
        idx: 11,
        score: 0.0981,
      },
      {
        idx: 8,
        score: 0.0786,
      },
      {
        idx: 6,
        score: 0.076,
      },
      {
        idx: 9,
        score: 0.0415,
      },
      {
        idx: 7,
        score: 0.013,
      },
      {
        idx: 1,
        score: -0.0126,
      },
      {
        idx: 0,
        score: -0.0281,
      },
      {
        idx: 2,
        score: -0.0754,
      },
    ],
  },
  {
    id: "bread",
    label: "how bread rises",
    text: "how bread dough rises before baking",
    baseX: 0.6295,
    baseY: 0.604,
    matches: [
      {
        idx: 6,
        score: 0.6063,
      },
      {
        idx: 7,
        score: 0.0598,
      },
      {
        idx: 8,
        score: 0.0571,
      },
      {
        idx: 10,
        score: 0.0517,
      },
      {
        idx: 9,
        score: -0.006,
      },
      {
        idx: 5,
        score: -0.0114,
      },
      {
        idx: 4,
        score: -0.0119,
      },
      {
        idx: 1,
        score: -0.0224,
      },
      {
        idx: 11,
        score: -0.0353,
      },
      {
        idx: 3,
        score: -0.0544,
      },
      {
        idx: 2,
        score: -0.0743,
      },
      {
        idx: 0,
        score: -0.0844,
      },
    ],
  },
  {
    id: "vector-db",
    label: "vector database search",
    text: "nearest neighbor search over embeddings",
    baseX: 0.331,
    baseY: 0.6295,
    matches: [
      {
        idx: 8,
        score: 0.6499,
      },
      {
        idx: 9,
        score: 0.3785,
      },
      {
        idx: 4,
        score: 0.0725,
      },
      {
        idx: 1,
        score: 0.0648,
      },
      {
        idx: 2,
        score: 0.0481,
      },
      {
        idx: 10,
        score: 0.0394,
      },
      {
        idx: 3,
        score: 0.029,
      },
      {
        idx: 5,
        score: 0.0235,
      },
      {
        idx: 7,
        score: 0.0103,
      },
      {
        idx: 6,
        score: -0.0059,
      },
      {
        idx: 11,
        score: -0.0166,
      },
      {
        idx: 0,
        score: -0.0355,
      },
    ],
  },
  {
    id: "river-bank",
    label: "river bank",
    text: "land beside a river",
    baseX: 0.7586,
    baseY: 0.608,
    matches: [
      {
        idx: 10,
        score: 0.6657,
      },
      {
        idx: 11,
        score: 0.2088,
      },
      {
        idx: 5,
        score: 0.119,
      },
      {
        idx: 4,
        score: 0.1086,
      },
      {
        idx: 9,
        score: 0.1036,
      },
      {
        idx: 3,
        score: 0.1016,
      },
      {
        idx: 2,
        score: 0.1002,
      },
      {
        idx: 8,
        score: 0.0913,
      },
      {
        idx: 1,
        score: 0.0631,
      },
      {
        idx: 0,
        score: 0.0275,
      },
      {
        idx: 7,
        score: 0.0004,
      },
      {
        idx: 6,
        score: -0.0235,
      },
    ],
  },
  {
    id: "money-bank",
    label: "money bank",
    text: "bank loans deposits and accounts",
    baseX: 0.8737,
    baseY: 0.5687,
    matches: [
      {
        idx: 11,
        score: 0.6021,
      },
      {
        idx: 10,
        score: 0.4076,
      },
      {
        idx: 6,
        score: 0.0873,
      },
      {
        idx: 0,
        score: 0.0328,
      },
      {
        idx: 2,
        score: 0.0245,
      },
      {
        idx: 5,
        score: 0.0152,
      },
      {
        idx: 9,
        score: 0.0107,
      },
      {
        idx: 7,
        score: -0.0102,
      },
      {
        idx: 8,
        score: -0.0365,
      },
      {
        idx: 4,
        score: -0.0375,
      },
      {
        idx: 3,
        score: -0.0653,
      },
      {
        idx: 1,
        score: -0.077,
      },
    ],
  },
];

export const CONTEXTUAL_EXAMPLES: EmbeddingContextualExample[] = [
  {
    word: "bank",
    note: "Same surface word, different surrounding words, different vector neighborhood.",
    anchors: [
      {
        label: "river",
        baseX: 0.7105,
        baseY: 0.3287,
      },
      {
        label: "water",
        baseX: 0.5725,
        baseY: 0.6578,
      },
      {
        label: "shore",
        baseX: 0.7693,
        baseY: 0.5145,
      },
      {
        label: "money",
        baseX: 0.2326,
        baseY: 0.88,
      },
      {
        label: "loan",
        baseX: 0.1,
        baseY: 0.7031,
      },
      {
        label: "account",
        baseX: 0.2668,
        baseY: 0.72,
      },
      {
        label: "capital city",
        baseX: 0.7715,
        baseY: 0.1369,
      },
      {
        label: "country",
        baseX: 0.8956,
        baseY: 0.3074,
      },
      {
        label: "past tense",
        baseX: 0.3884,
        baseY: 0.8133,
      },
    ],
    contexts: [
      {
        label: "river bank",
        phrase: "The canoe scraped against the river bank after the storm.",
        baseX: 0.6366,
        baseY: 0.451,
        nearestAnchors: [
          {
            label: "river",
            score: 0.4003,
          },
          {
            label: "shore",
            score: 0.214,
          },
          {
            label: "water",
            score: 0.1933,
          },
        ],
      },
      {
        label: "money bank",
        phrase: "The bank approved the loan and opened a savings account.",
        baseX: 0.1295,
        baseY: 0.5255,
        nearestAnchors: [
          {
            label: "loan",
            score: 0.5657,
          },
          {
            label: "account",
            score: 0.3173,
          },
          {
            label: "river",
            score: 0.1951,
          },
        ],
      },
    ],
  },
  {
    word: "capital",
    note: "Context decides whether capital means a city, money, or something else.",
    anchors: [
      {
        label: "river",
        baseX: 0.7105,
        baseY: 0.3287,
      },
      {
        label: "water",
        baseX: 0.5725,
        baseY: 0.6578,
      },
      {
        label: "shore",
        baseX: 0.7693,
        baseY: 0.5145,
      },
      {
        label: "money",
        baseX: 0.2326,
        baseY: 0.88,
      },
      {
        label: "loan",
        baseX: 0.1,
        baseY: 0.7031,
      },
      {
        label: "account",
        baseX: 0.2668,
        baseY: 0.72,
      },
      {
        label: "capital city",
        baseX: 0.7715,
        baseY: 0.1369,
      },
      {
        label: "country",
        baseX: 0.8956,
        baseY: 0.3074,
      },
      {
        label: "past tense",
        baseX: 0.3884,
        baseY: 0.8133,
      },
    ],
    contexts: [
      {
        label: "capital city",
        phrase: "Berlin is the capital city of Germany.",
        baseX: 0.9,
        baseY: 0.12,
        nearestAnchors: [
          {
            label: "capital city",
            score: 0.5369,
          },
          {
            label: "country",
            score: 0.1653,
          },
          {
            label: "river",
            score: 0.1265,
          },
        ],
      },
      {
        label: "capital investment",
        phrase: "The company raised capital to fund new equipment.",
        baseX: 0.2281,
        baseY: 0.4139,
        nearestAnchors: [
          {
            label: "money",
            score: 0.2188,
          },
          {
            label: "capital city",
            score: 0.2111,
          },
          {
            label: "loan",
            score: 0.1976,
          },
        ],
      },
    ],
  },
];
