import type { Metadata } from "next";

import { LabInfoPanel } from "@/features/lab/components/lab-info-panel";
import { Spectre } from "@/features/lab/components/spectre";

export const metadata: Metadata = {
  title: "Spectre",
  description: "The aperiodic monotile. One shape, infinite non-repeating tiling.",
  alternates: { canonical: "/lab/spectre" },
};

export default function SpectrePage() {
  return (
    <>
      <Spectre />
      <div className="pointer-events-none fixed bottom-6 left-5 z-10 select-none md:left-8">
        <p className="font-mono text-[10px] uppercase tracking-[0.15em] text-foreground/40">
          spectre
        </p>
        <p className="font-mono text-[9px] uppercase tracking-[0.2em] text-foreground/20">
          aperiodic monotile (2023)
        </p>
      </div>
      <LabInfoPanel>
        <p>
          In 2023, Smith, Myers, Kaplan, and Goodman-Strauss proved that a single tile shape can
          cover the plane with no repeating pattern and no reflections. This solved the
          &quot;einstein problem,&quot; open since 1961.
        </p>
        <p>
          The tiling is generated by recursive substitution: each supertile contains smaller copies
          of itself. The hierarchy never repeats, producing aperiodicity at every scale. Colors
          indicate the metatile type at each level.
        </p>
        <p className="border-t border-foreground/10 pt-2">
          <a
            href="https://arxiv.org/abs/2305.17743"
            target="_blank"
            rel="noopener noreferrer"
            className="underline underline-offset-2 hover:text-foreground/70"
          >
            Smith et al. (2023)
          </a>
          {" · "}
          <a
            href="https://en.wikipedia.org/wiki/Einstein_problem"
            target="_blank"
            rel="noopener noreferrer"
            className="underline underline-offset-2 hover:text-foreground/70"
          >
            Wikipedia
          </a>
        </p>
      </LabInfoPanel>
    </>
  );
}
